services:
  - type: web
    name: bluevision-realtors
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true